version: '3.7'

services:
  redmine:
    build: ./redmine
    restart: always
    ports:
      - '3333:3000'
    depends_on:
      - mysql
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: $MYSQL_PASSWORD
      REDMINE_SECRET_KEY_BASE: $REDMINE_SECRET
  
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
        - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: redmine
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: $PHPMYADMIN_MAX_UPLOAD

volumes:
    data:
        driver: local
